server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-management?serverTimeZone=GMT%2bB
    username: root
    password: 111111

# sql 日志（方式一）
logging:
  level:
    # mapper接口所在的包
    com.example.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml












# sql 日志（方式二） 需要添加 mybatis-plus 依赖
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl